---
abstract: 'Conversion class between MARC record and Wikidata object.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  File::Object: 0
  MARC::File::XML: 0
  MARC::Record: 0
  Perl6::Slurp: 0
  Test::More: 0
  Test::NoWarnings: 0
  Test::Warn: 0
  Unicode::UTF8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.21'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MARC-Convert-Wikidata
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Utils: 0.03
  Data::Kramerius: 0
  DateTime: 0
  English: 0
  Error::Pure: 0
  MARC::Convert::Wikidata::Object: 0.08
  MARC::Convert::Wikidata::Object::ExternalId: 0
  MARC::Convert::Wikidata::Object::ISBN: 0.07
  MARC::Convert::Wikidata::Object::Kramerius: 0
  MARC::Convert::Wikidata::Object::People: 0
  MARC::Convert::Wikidata::Object::Publisher: 0
  MARC::Convert::Wikidata::Object::Series: 0.09
  MARC::Leader: 0
  Mo::utils: 0.08
  Readonly: 0
  Roman: 0
  URI: 0
  Unicode::UTF8: 0
  Wikibase::Datatype: 0
  perl: 5.6.2
resources:
  bugtracker: https://github.com/michal-josef-spacek/MARC-Convert-Wikidata/issues
  homepage: https://github.com/michal-josef-spacek/MARC-Convert-Wikidata
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/MARC-Convert-Wikidata
version: '0.23'
